### ISSUE TITLE
[Feature] Support built-in scripts

### ISSUE THREAD

**Issue by nonunknown** [Rybadour/NodeConnectorGodot#3]
I'm clicking at connect nodes, and cannot see changes, unfocus would be close and reopen the engine?

![Screenshot from 2020-04-09 09-38-55](https://user-images.githubusercontent.com/58845030/78895976-1b260f80-7a46-11ea-8984-15880b8ab7cd.png)

Using a built-in script!
![Screenshot from 2020-04-09 09-40-36](https://user-images.githubusercontent.com/58845030/78896019-309b3980-7a46-11ea-9583-570172b5c0ef.png)

**edit**

Closing and reopening godot worked, but only for non-built-in script, if using built-in the closing/opening does not work

maybe is related to this issue: https://github.com/godotengine/godot/issues/10946

**Comment by Rybadour** [comment]
Looks like your problem is deeper than that though. Is your script really called "Control.tscn::1"? Because that's what the message says it modified.

**Comment by nonunknown** [comment]
cuz its a built-in script, currently it seems not to support built-in, so only works with external scripts

**Comment by Rybadour** [comment]
Ah I'll have to do some research about built-in scripts. Never heard of
that feature before!

-- Ryan

**Comment by nonunknown** [comment]
Thy are Just scripts Just instead of .gd Thy are Inside of .tscn files

Em qui, 9 de abr de 2020 12:57, Ryan Badour <notifications@github.com>
escreveu:

**Comment by Rybadour** [comment]
If you view the file outside of Godot (say with Notepad, Vim, or some other IDE). Do you see the code added correctly?

**Comment by nonunknown** [comment]
I'll check


Em qui, 9 de abr de 2020 14:09, Ryan Badour <notifications@github.com>
escreveu:

**Comment by nonunknown** [comment]
@Rybadour 

![trial](https://user-images.githubusercontent.com/58845030/78925228-83d6b180-7a71-11ea-8f48-e2a210b251f3.gif)

**Comment by Rybadour** [comment]
Interesting, but I was curious if the modification to the file worked? I
mean it should fail if it didn't find the _ready function or the extends
line so it must have worked. If refocusing Godot didn't work though I'm not
sure what we can do.

**Comment by Rybadour** [comment]
FYI: I tried to use my plugin with a basic scene using a built-in script and it didn't work. I'm updating this issue to be about adding support for built-in scripts as it's not just about them not updating. The plugin cannot currently support them.

**Comment by nonunknown** [comment]
Remember that builtin scenes Onlyupdates when reloading the scene

Em sex, 10 de abr de 2020 11:20, Ryan Badour <notifications@github.com>
escreveu:

**Comment by Rybadour** [comment]
Fixed! I added support for built-in scripts in the last commit.
