### ISSUE TITLE
[BUG] Selecting 1 node at time will cause replacement on script

### ISSUE THREAD

**Issue by nonunknown** [Rybadour/NodeConnectorGodot#9]
**Godot Version** 
3.2.2 beta 1

**OS version**
ubuntu 19.10 x64

**Problem**
If you for example, select Button A, Press F9, button B, press F9 and so on
will make the plugin replace the onready var declaration
and will not place anthing on the function _ready()

**Comment by Rybadour** [comment]
Hmm that doesn't make sense. If that were true than you couldn't run this with an existing ready method at all. Perhaps the second thing you selected wasn't a button or text edit? The plugin currently only adds signal handles for those two node types.

**Comment by nonunknown** [comment]
ohhh I didnt know that!
